name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Hmm ga tau lagi
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        key: ${{ secrets.FTP_KEY }}
        port: 21
        script: |
          PATH=$PATH:/home/${{secrets.FTP_USERNAME}}/.nvm/versions/node/v16.20.0/bin
          npx pm2 restart ./app.js
